### ISSUE TITLE
On-chain storage will scale to 1000s of users?

### ISSUE THREAD

**Issue by sdgandhi** [a16z/zkdocs#3]
This is a beautiful practical application for zk proofs. From my understanding, all the user data for this dapp is stored on-chain to make it decentralized obviously. Now even with cheaper EVM compatible chains, supporting 1000s of users would incur large storage costs ($64k/mb on ethereum).

How would you recommend scaling the storage for this type of application?

**Comment by sragss** [comment]
Thanks! Yes there is quite a substantial data overhead per user. 

There's a few ways I think about scalability here. 

First, I would suggest that it's not all that expensive today on mainnet or other EVM options. The cost of existing document verification workflows today often requires faxing / printing / mailing and hours human labor for verification / authentication. It is hard to quantify specifically, but one can imagine a cost hundreds of dollars per submission / verification. It's easy to see how zkDocs is an order of magnitude cheaper.

Second, zkDocs moves the verification work from the verifier to the submitter. This includes the gas costs for storage per submission: When a submitter fills out a document and commits to it, they update two 32-byte storage slots for each field. One can think of this as an application fee. Submitters pay some cost to use EVM blockspace, but as the number of submitters scales, the verifying institution's costs remain constant. 

Now some actual gas cost reduction strategies.

Adjusting the data model:
- Create a merkle tree for commitments and only publish the merkle root to chain
- If you do not need dynamic attesters per field or trust your attesters you can drop the `requiredCommitmentAttestations` map and reduce gas usage by ~50%

Deployment:
- Deploy on an alt-EVM chain with cheaper gas
- Deploy on a rollup which doesn't commit all state to mainnet

**Comment by sdgandhi** [comment]
Gotcha, this is practical and makes sense.
